// src/lib/header/Header.svelte
<script lang="ts">
	import Filters from './Filters.svelte';

	import { page } from '$app/stores';

	import Icon from 'heroicons-for-svelte';
	import { BookOpen } from 'heroicons-for-svelte/icons/outline';
</script>

<header
	class="flex justify-between py-2 sticky top-0 bg-red-100 opacity-100 z-50 border-b-2 border-red-900"
>
	<div class="self-center">
		<h1 class="text-2xl font-bold text-red-900">
			<a href="/">Spells</a>
		</h1>
	</div>

	<div class="self-center flex">
		<Filters />
	</div>

	<nav class="self-center">
		<!-- TODO put something else here? github link? -->
		<li
			class:active={$page.url.pathname === '/'}
			class="bg-red-300 rounded-full h-10 w-10 flex justify-center"
		>
			<a sveltekit:prefetch href="/prepared" class="text-3xl self-center text-red-900">
				<Icon icon={BookOpen} />
			</a>
		</li>
	</nav>
</header>

<style>
	li {
		list-style: none;
	}
</style>

// components/Header.jsx
import Link from "next/link"
import { useRef } from "react"
import { useContext } from "react"
import { SpellDispatch } from "../pages/_app"

export default function Header() {
  const spellDispatch = useContext(SpellDispatch)

  // Search timer
  const timeout = useRef(0)

  const _handleSearch = (e) => {
    // Reset timeout
    clearTimeout(timeout)

    // After a moment from last input, dispatch search
    timeout = setTimeout(() => {
      spellDispatch({ type: "search", payload: e.target.value })
    }, 500)
  }

  return (
    <header className="md:px-2 text-lg sticky top-0 z-50 md:space-y-2">
      <div className="w-full flex justify-between bg-primaryLight-300 bg-opacity-90 backdrop-blur-md shadow-md shadow-primaryLight-100 md:rounded-b-2xl">
        <h1 className="p-2 pl-4 font-bold">
          <Link href="/">D&D Spellbook</Link>
        </h1>
        <nav className="p-2">
          <ul>
            <li>
              <Link href="/">Prepared Spells</Link>
            </li>
          </ul>
        </nav>
      </div>
      <div className="block w-full bg-primaryLight-300 bg-opacity-90 backdrop-blur-md shadow-md shadow-primaryLight-100 md:rounded-2xl">
        <div className="p-2">
          <input
            className="p-2 border-none rounded-xl focus:outline-none"
            type="search"
            onChange={_handleSearch}
            placeholder="Search..."
          />
        </div>
      </div>
    </header>
  )
}
